name: Working Dirs & Shells
on: [push]
jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display Working Directory & List Files
        run: |
          pwd
          ls -a
          echo $GITHUB-SHA
          echo $GITHYB_REPOSITORY
          echo $GITHUB_WORKSPACE

  display-wd-info-windows:
    runs-on: windows-latest
    steps:
      - name: Display Working Directory & List Files
        run: |
          pwd
          ls -a
          echo $GITHUB-SHA
          echo $GITHYB_REPOSITORY
          echo $GITHUB_WORKSPACE          